# Generated by Django 4.0.5 on 2022-07-10 15:16

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0002_alter_signup_block_unblock_alter_signup_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_name', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('Video_link', embed_video.fields.EmbedVideoField()),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
