# Generated by Django 4.0.5 on 2022-07-10 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='videocommets',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raxit.videocommets')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raxit.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
