# Generated by Django 4.0.5 on 2022-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0005_alter_signup_block_unblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='block_unblock',
            field=models.CharField(choices=[('block', 'Block'), ('unblock', 'Unblock')], default='unblock', max_length=10),
        ),
    ]
